### ISSUE TITLE
Oooooops!

### ISSUE THREAD

**Issue by PeterHouseJr** [thomasnordquist/MQTT-Explorer#666]
MQTT Explorer will not start and shows the following message (the text contents are pasted below).  After a reboot, same issue.  Choosing the "Start Fresh" finally button worked but totally lost my connection information.

![image](https://user-images.githubusercontent.com/67009958/180827474-b30f0ae5-5fea-4846-9af4-d3e7c1cf56bb.png)

```
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bqos%2C%20topic%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ba (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10282:312)
    at x (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10283:166)
    at Bf (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10406:39)
    at p (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10410:49)
    at v (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10412:145)
    at file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10416:131
    at S (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10433:72)
    at Tg (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10450:151)
    at bi (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10501:22)
    at ci (file:///C:/Program%20Files/WindowsApps/51031thomas.nordquist.MQTT-Explorer_0.3.5.0_x64__0vh81zz42j0x6/app/resources/app.asar/app/build/vendors.bundle.js:10502:284)
```

**Comment by JamesJian-tech** [comment]
Crash

**Comment by SKLD-OH3** [comment]
use "Start Fresh" on my system it works, but since 3 days no thing no item will be monitored. Could be an issue of Mosquitto.
